const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE='vcp_psychologist_workspace_v1';
const todayISO=()=>new Date().toISOString().slice(0,10);
const isoOffset=(days)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nl=(v='')=>esc(v).replace(/\n/g,'<br>');
const fmtDate=(v,withYear=true)=>{if(!v)return 'не назначено';const d=new Date(`${v}T12:00:00`);return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',...(withYear?{year:'numeric'}:{})}).format(d)};
const shortDate=(v)=>{if(!v)return '—';const d=new Date(`${v}T12:00:00`);return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit'}).format(d)};
const statusLabels={active:'В работе',pause:'Пауза',completed:'Завершено'};
const statusClass=(s)=>['active','pause','completed'].includes(s)?s:'active';

const scenarios={
 hire:{title:'Работа в найме',short:'Найм',icon:'▢',text:'Рост, смена роли или компании без решения вслепую.'},
 return:{title:'Возвращение после перерыва',short:'После перерыва',icon:'◔',text:'Реалистичный темп, формат и восстановление профессиональной опоры.'},
 freelance:{title:'Фриланс и частная практика',short:'Фриланс',icon:'▱',text:'Стабильность, цена, клиенты и границы без перегрузки.'},
 experienced:{title:'Карьера после 45+',short:'45+',icon:'45+',text:'Переход без обнуления опыта, статуса, дохода и сил.'},
 expert:{title:'Эксперт и практик',short:'Эксперт',icon:'☆',text:'Перевод опыта в понятную услугу, формат или пилот.'}
};

const questionSets={
 hire:[
  {key:'problem',kicker:'Текущая ситуация',title:'Что в работе стало главным источником тупика?',help:'Это помогает отделить проблему профессии от проблемы конкретного места.',options:[['money','Доход и условия оплаты'],['growth','Нет роста и понятной перспективы'],['tasks','Сами задачи больше не интересуют'],['manager','Руководитель, культура или отношения'],['overload','Перегрузка и нехватка сил']]},
  {key:'tried',kicker:'Предыдущие попытки',title:'Что клиент уже пробовал изменить?',help:'Маршрут не должен повторять совет, который уже проверяли.',options:[['talk','Разговор о повышении или условиях'],['internal','Внутренний переход или конкурс'],['training','Обучение и новые навыки'],['applications','Отклики и сравнение рынка'],['load','Изменение нагрузки'],['nothing','Пока ничего конкретного']]},
  {key:'protect',kicker:'Ограничение',title:'Что сейчас нельзя потерять?',help:'Этот ответ отсекает рискованные рекомендации.',options:[['income','Стабильный доход'],['schedule','Подходящий график'],['status','Статус и уровень ответственности'],['remote','Удалённость или близость к дому']]},
  {key:'preserve',kicker:'Опора',title:'Что в нынешней работе всё ещё подходит?',help:'Эту часть не нужно выбрасывать вместе с проблемой.',options:[['field','Профессиональная сфера'],['tasks','Отдельные задачи'],['team','Команда и взаимодействие'],['stability','Предсказуемость и устойчивость']]},
  {key:'time',kicker:'Посильный формат',title:'Какой шаг реально поместится в ближайшие 72 часа?',help:'Размер действия должен соответствовать энергии и времени.',options:[['10','10 минут'],['30','30 минут'],['60','Около часа'],['talk','Один короткий разговор']]}
 ],
 return:[
  {key:'priority',kicker:'Текущая задача',title:'Что сейчас важнее всего?',help:'Не выбор на всю жизнь, а ближайшая задача.',options:[['income','Снова получать свой доход'],['identity','Вернуть ощущение, что я специалист'],['contact','Постепенно выйти из домашней изоляции'],['direction','Понять, возвращаться ли в прежнюю сферу']]},
  {key:'time',kicker:'Реальная нагрузка',title:'Сколько времени действительно есть на возвращение?',help:'План должен учитывать реальный, а не воображаемый график.',options:[['10','10–20 минут в день'],['60','Около часа в день'],['blocks','2–3 часа несколько раз в неделю'],['unstable','График пока меняется']]},
  {key:'protect',kicker:'Ограничение',title:'Что нельзя нарушить?',help:'Первый шаг должен выдержать реальную жизнь клиента.',options:[['family','Режим ребёнка и семейные обязанности'],['income','Нельзя долго работать бесплатно'],['flex','Нужна удалённая или гибкая работа'],['energy','Нельзя брать высокую нагрузку']]},
  {key:'resource',kicker:'Опора',title:'На что уже можно опереться?',help:'Перерыв не обнуляет опыт, но ресурс важно назвать конкретно.',options:[['profession','Профессиональный опыт до перерыва'],['life','Организация, общение и решение бытовых задач'],['learning','Быстро восстанавливаю знания и учусь'],['unknown','Клиенту трудно увидеть свой ресурс']]},
  {key:'step',kicker:'Первый эксперимент',title:'Какой шаг действительно посилен на этой неделе?',help:'Выбираем не самый правильный, а выполнимый шаг.',options:[['message','Написать бывшему коллеге'],['vacancies','Сохранить три вакансии'],['resume','Обновить один блок резюме'],['trial','Выполнить маленькую пробную задачу']]}
 ],
 freelance:[
  {key:'stage',kicker:'Стадия',title:'На какой стадии находится практика?',help:'Советы для первых заказов и для перегрузки не могут быть одинаковыми.',options:[['none','Заказов ещё нет'],['rare','Есть редкие случайные заказы'],['stable','Заказы идут относительно стабильно'],['overload','Есть перегрузка и потолок']]},
  {key:'bottleneck',kicker:'Узкое место',title:'Где система ломается чаще всего?',help:'Рост начинается с точного узкого места.',options:[['leads','Мало обращений'],['sales','Трудно продавать и договариваться'],['price','Цена слишком низкая'],['production','Заказ выполняется слишком долго'],['returns','Клиенты не возвращаются'],['boundaries','Правки и границы размыты']]},
  {key:'duration',kicker:'Экономика времени',title:'Сколько обычно занимает один заказ?',help:'Без времени невозможно понять реальную цену работы.',options:[['2h','До двух часов'],['day','Около рабочего дня'],['days','Несколько дней'],['unknown','Часто дольше плана']]},
  {key:'repeat',kicker:'Повторяемость',title:'Что чаще всего повторяется в проектах?',help:'Это возможная основа специализации или пакета.',options:[['task','Одна и та же задача'],['client','Похожий тип клиента'],['result','Похожий результат'],['none','Устойчивой повторяемости пока нет']]},
  {key:'experiment',kicker:'Проверка',title:'Что клиент готов проверить за 72 часа?',help:'Проверка должна соответствовать стадии.',options:[['interview','Интервью о реальной проблеме'],['offer','Одно конкретное предложение'],['price','Новую цену или минимальный пакет'],['boundaries','Границы работы и правок']]}
 ],
 experienced:[
  {key:'reason',kicker:'Причина перехода',title:'Почему изменения нужны именно сейчас?',help:'Маршрут определяет причина, а не возраст.',options:[['cut','Сокращение или риск потери работы'],['ceiling','Потолок и отсутствие роста'],['load','Физическая или управленческая нагрузка'],['interest','Потеря интереса к прежней роли'],['move','Переезд или изменение условий жизни']]},
  {key:'horizon',kicker:'Финансовый горизонт',title:'Когда нужен устойчивый доход?',help:'Это отсекает слишком долгие и опасные траектории.',options:[['now','Нужен сейчас'],['2m','В течение 1–2 месяцев'],['6m','Можно проверять 3–6 месяцев'],['reserve','Есть резерв для спокойного перехода']]},
  {key:'protect',kicker:'Профессиональный капитал',title:'Что точно нельзя обнулить?',help:'Опыт должен перейти в новый формат, а не исчезнуть.',options:[['income','Доход'],['status','Экспертный статус'],['experience','Накопленный опыт'],['schedule','График и образ жизни'],['health','Здоровье и силы']]},
  {key:'tech',kicker:'Цифровая готовность',title:'Как клиент чувствует себя с современными технологиями?',help:'Проверяем реальный разрыв, а не стереотип о возрасте.',options:[['confident','Работает уверенно'],['basic','Осваивает базовые инструменты'],['help','Нужна поддержка и обучение']]},
  {key:'format',kicker:'Подходящий формат',title:'Какой формат работы сейчас реалистичнее?',help:'Желаемая нагрузка важнее цифры в паспорте.',options:[['full','Полный рабочий день'],['hybrid','Гибрид или гибкий график'],['project','Проектная занятость'],['mentor','Наставничество или экспертная роль']]}
 ],
 expert:[
  {key:'stage',kicker:'Стадия',title:'Где сейчас находится эксперт?',help:'После ответа расходятся карьерная и продуктовая ветки.',options:[['forming','Формирует практику'],['few','Есть единичные клиенты'],['system','Есть повторяемая услуга'],['overload','Перегружен индивидуальной работой'],['digital','Хочет создать цифровой продукт']]},
  {key:'paid',kicker:'Рыночное основание',title:'За какой результат уже платили?',help:'Знания сами по себе не доказывают готовность продукта.',options:[['consult','За консультацию или разбор'],['solution','За конкретное решение задачи'],['support','За сопровождение изменений'],['none','Пока не платили']]},
  {key:'evidence',kicker:'Доказательства',title:'Есть ли повторяемое подтверждение результата?',help:'Обещание должно опираться на факты.',options:[['cases','Есть несколько похожих кейсов'],['reviews','Есть отзывы и описания изменений'],['metrics','Есть измеримые результаты'],['none','Подтверждений пока мало']]},
  {key:'audience',kicker:'Доступ к людям',title:'Кому можно предложить первую проверку?',help:'Пилот невозможен без доступа к аудитории.',options:[['clients','Текущим или прошлым клиентам'],['channel','Своему каналу или базе'],['partners','Через партнёров'],['none','Прямого доступа пока нет']]},
  {key:'manual',kicker:'Границы формата',title:'Сколько ручной работы допустимо?',help:'Это определяет формат, цену и этические границы.',options:[['one','Только 1:1'],['group','Можно работать с группой'],['review','Допустима проверка заданий и обратная связь'],['self','Нужен почти самостоятельный продукт']]}
 ]
};

function seedData(){
 const c1='client_anna',c2='client_olga',c3='client_sergey';
 return {
  version:1,
  activeClientId:c1,
  clients:[
   {id:c1,name:'Анна К.',age:37,contact:'telegram: @anna_demo',status:'active',request:'Хочет уйти из найма, но боится потерять устойчивый доход и повторить неудачный переход.',context:'Руководит небольшим отделом. Высокая нагрузка, двое детей, финансовый резерв ограничен. Интересуется частной практикой, но не проверяла спрос.',formulation:'Напряжение поддерживается конфликтом между потребностью в автономии и требованием финансовой безопасности. Большое решение подменяет серию малых проверок.',resources:'Управленческий опыт, способность структурировать хаос, поддержка супруга, профессиональные контакты.',constraints:'Нельзя резко снижать доход; доступно не более 3 часов в неделю; высокая усталость к вечеру.',attention:'Отслеживать истощение и тенденцию брать слишком большие обязательства.',nextSession:isoOffset(1),nextSessionTime:'11:00',createdAt:isoOffset(-46)},
   {id:c2,name:'Ольга М.',age:45,contact:'email: olga.demo@example.com',status:'active',request:'Возвращение в профессию после длительного перерыва и переезда.',context:'Опыт в образовании. Уверенность снижена, цифровые инструменты осваивает постепенно.',formulation:'Самооценка профессиональной пригодности опирается на сравнение с более молодыми кандидатами, а не на фактические компетенции.',resources:'Педагогический опыт, терпение, навыки работы с людьми, готовность учиться.',constraints:'Нужен гибкий график; доход желателен в течение двух месяцев.',attention:'Не ускорять темп за счёт перегрузки и бесплатной работы.',nextSession:isoOffset(3),nextSessionTime:'16:30',createdAt:isoOffset(-24)},
   {id:c3,name:'Сергей П.',age:33,contact:'телефон: +7 900 000-00-00',status:'pause',request:'Стабилизировать фриланс и перестать соглашаться на бесконечные правки.',context:'Дизайнер, заказы есть, но прибыль непредсказуема.',formulation:'Неопределённые границы используются как способ снизить риск отказа клиента, но увеличивают перегрузку и раздражение.',resources:'Сильное портфолио, повторные клиенты, быстрый старт работы.',constraints:'Нет резерва на долгую перестройку системы продаж.',attention:'Проверить, не превращается ли стратегия избегания конфликта в хроническую перегрузку.',nextSession:'',nextSessionTime:'',createdAt:isoOffset(-70)}
  ],
  sessions:[
   {id:'s1',clientId:c1,date:isoOffset(-21),format:'Онлайн',duration:60,stateBefore:4,stateAfter:6,theme:'Уточнение запроса и цена резкого перехода',notes:'Клиентка связывает свободу только с увольнением. При обсуждении промежуточных форматов напряжение снижается.',hypothesis:'Поляризация «остаться или уйти» сокращает число доступных решений.',interventions:'Шкалирование риска; разделение проблемы работодателя, роли и формата работы.',homework:'Собрать три примера проектной занятости без увольнения.',nextFocus:'Проверить, какие критерии перехода действительно обязательны.'},
   {id:'s2',clientId:c1,date:isoOffset(-13),format:'Онлайн',duration:55,stateBefore:5,stateAfter:7,theme:'Критерии безопасного эксперимента',notes:'Сформулированы ограничения по времени и доходу. Клиентка впервые назвала допустимую стоимость эксперимента.',hypothesis:'Чёткие ограничения увеличивают субъективную управляемость.',interventions:'Матрица «сохранить — изменить — проверить».',homework:'Провести один разговор с потенциальным заказчиком без продажи.',nextFocus:'Разобрать реакцию на интервью и признаки реального спроса.'},
   {id:'s3',clientId:c1,date:isoOffset(-5),format:'Онлайн',duration:60,stateBefore:5,stateAfter:8,theme:'Первое интервью и страх оценки',notes:'Получен интерес к диагностическому разбору. Клиентка обесценивает результат, потому что собеседник знакомый.',hypothesis:'Критерий доказательства завышается после каждого подтверждения.',interventions:'Возврат к заранее определённым критериям эксперимента; фиксация наблюдаемых фактов.',homework:'Повторить интервью с двумя менее знакомыми людьми.',nextFocus:'Собрать предложение пилота с ограниченными границами.'},
   {id:'s4',clientId:c2,date:isoOffset(-12),format:'Очно',duration:60,stateBefore:3,stateAfter:5,theme:'Инвентаризация опыта после перерыва',notes:'Клиентка перечисляет обязанности, но почти не называет результаты.',hypothesis:'Опыт воспринимается как устаревший, потому что не переведён в язык современного рынка.',interventions:'Разбор ситуаций по схеме задача — действие — результат.',homework:'Описать три случая профессионального решения сложной ситуации.',nextFocus:'Перевести результаты в формулировки для резюме.'},
   {id:'s5',clientId:c3,date:isoOffset(-30),format:'Онлайн',duration:50,stateBefore:4,stateAfter:6,theme:'Границы правок',notes:'Выявлено отсутствие письменного критерия завершения работы.',hypothesis:'Страх потерять клиента сильнее оценки фактических затрат.',interventions:'Ролевой диалог о границах; расчёт времени последнего проекта.',homework:'Добавить два раунда правок в описание следующего заказа.',nextFocus:'Проверить реакцию клиента и собственное напряжение.'}
  ],
  goals:[
   {id:'g1',clientId:c1,title:'Проверить спрос на диагностический карьерный разбор без увольнения',metric:'Проведены 3 интервью; минимум у двух людей проблема узнаваема; зафиксированы формулировки их запроса.',deadline:isoOffset(12),status:'active',steps:[{id:'st1',text:'Составить 5 вопросов для интервью',done:true},{id:'st2',text:'Провести первое интервью',done:true},{id:'st3',text:'Провести ещё два интервью',done:false}]},
   {id:'g2',clientId:c2,title:'Вернуть профессиональный опыт в язык современного резюме',metric:'Сформулированы 5 результатов и собран один обновлённый блок резюме.',deadline:isoOffset(18),status:'active',steps:[{id:'st4',text:'Описать три профессиональные ситуации',done:true},{id:'st5',text:'Выделить действия и результаты',done:false}]},
   {id:'g3',clientId:c3,title:'Установить границы правок в новых заказах',metric:'В двух новых предложениях письменно указано число раундов правок.',deadline:isoOffset(-3),status:'active',steps:[{id:'st6',text:'Сформулировать правило правок',done:true},{id:'st7',text:'Использовать в следующем предложении',done:false}]}
  ],
  assessments:[]
 };
}

let data=loadData();
let ui={view:'dashboard',clientTab:'overview',clientSearch:'',clientStatus:'all',sessionSearch:'',assessmentDraft:null,lastFocus:null};

function loadData(){try{const raw=JSON.parse(localStorage.getItem(STORAGE));if(raw&&raw.version===1&&Array.isArray(raw.clients))return raw;}catch{}return seedData();}
function saveData(){try{localStorage.setItem(STORAGE,JSON.stringify(data));}catch{}refreshChrome();}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
function clientById(id){return data.clients.find(c=>c.id===id)}
function activeClient(){return clientById(data.activeClientId)||data.clients[0]||null}
function clientSessions(id){return data.sessions.filter(s=>s.clientId===id).sort((a,b)=>b.date.localeCompare(a.date))}
function clientGoals(id){return data.goals.filter(g=>g.clientId===id)}
function clientAssessments(id){return data.assessments.filter(a=>a.clientId===id).sort((a,b)=>b.date.localeCompare(a.date))}
function initials(name=''){return name.split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'К'}
function truncate(v='',n=120){return v.length>n?v.slice(0,n-1)+'…':v}
function openModal(id,opener){const m=$(id);if(!m)return;ui.lastFocus=opener||document.activeElement;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>m.querySelector('input,select,textarea,button')?.focus(),20)}
function closeModal(m){if(typeof m==='string')m=$(m);if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=$('#assessmentOverlay').classList.contains('open')?'hidden':'';ui.lastFocus?.focus?.()}
function refreshChrome(){
 $('#clientsCountBadge').textContent=data.clients.filter(c=>c.status==='active').length;
 const c=activeClient();
 $('#activeClientMini').innerHTML=c?`<small>Выбранный клиент</small><strong>${esc(c.name)}</strong><p>${esc(truncate(c.request||'Запрос не заполнен',72))}</p><div class="mini-actions"><button data-mini-action="open">Карточка</button><button data-mini-action="session">Сессия</button></div>`:'';
 $$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===ui.view));
 populateClientSelects();
}
function populateClientSelects(){
 const options=data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 ['#sessionClientSelect','#goalClientSelect'].forEach(id=>{const s=$(id);if(s){const old=s.value;s.innerHTML=options;if(clientById(old))s.value=old;else if(activeClient())s.value=activeClient().id;}});
}
function setPage(eyebrow,title){$('#pageEyebrow').textContent=eyebrow;$('#pageTitle').textContent=title;document.title=`${title} — Точка опоры`;}
function setView(view){ui.view=view;refreshChrome();renderView();window.scrollTo({top:0,behavior:'smooth'})}

function renderView(){
 const root=$('#viewRoot');
 if(ui.view==='dashboard')renderDashboard(root);
 else if(ui.view==='clients')renderClients(root);
 else if(ui.view==='sessions')renderSessions(root);
 else if(ui.view==='client')renderClient(root);
 else if(ui.view==='assessment')renderAssessmentHub(root);
 else if(ui.view==='plan')renderPlan(root);
 else if(ui.view==='dynamics')renderDynamics(root);
 else if(ui.view==='templates')renderTemplates(root);
 else if(ui.view==='settings')renderSettings(root);
 refreshChrome();
}

function renderDashboard(root){
 setPage('Рабочий кабинет','Обзор практики');
 const active=data.clients.filter(c=>c.status==='active').length;
 const month=todayISO().slice(0,7);const monthSessions=data.sessions.filter(s=>s.date.startsWith(month)).length;
 const openTasks=data.goals.flatMap(g=>g.steps||[]).filter(s=>!s.done).length;
 const attention=data.clients.filter(c=>c.status==='active'&&c.attention).length;
 const upcoming=data.clients.filter(c=>c.nextSession&&c.nextSession>=todayISO()).sort((a,b)=>(a.nextSession+a.nextSessionTime).localeCompare(b.nextSession+b.nextSessionTime)).slice(0,5);
 const recent=[...data.sessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
 root.innerHTML=`
  <div class="dashboard-grid">
   <section class="panel hero-panel"><div class="hero-content"><div class="hero-eyebrow"><i></i> Структурировать работу, не превращая её в бюрократию</div><h2>Клиент, сессии, гипотезы и шаги — <em>в одной рабочей карте.</em></h2><p>Кабинет хранит историю встреч, помогает связывать запрос с наблюдениями, фиксировать проверяемые договорённости и видеть динамику по выбранному клиенту.</p><div class="hero-actions"><button class="primary-button" data-action="add-session">Записать новую сессию</button><button class="quiet-button" data-action="open-active-client">Открыть карточку клиента</button></div></div></section>
   <section class="panel today-panel"><div class="panel-head"><div><span class="section-label">Ближайшие встречи</span><h2>Расписание</h2></div><button class="text-button" data-action="view-sessions">Все сессии</button></div><div class="today-list">${upcoming.length?upcoming.map(c=>`<article class="today-item" data-action="open-client" data-id="${c.id}"><div class="today-time">${esc(c.nextSessionTime||'—')}</div><div><strong>${esc(c.name)}</strong><p>${fmtDate(c.nextSession,false)} · ${esc(truncate(c.request||'',62))}</p></div><span class="status-chip ${statusClass(c.status)}">${statusLabels[c.status]}</span></article>`).join(''):`<div class="empty-state"><strong>Встреч нет</strong><p>Добавьте следующую дату в карточке клиента.</p></div>`}</div></section>
  </div>
  <div class="metric-row">
   <article class="metric-card"><small>Клиенты в работе</small><strong>${active}</strong><span>активных карточек</span></article>
   <article class="metric-card"><small>Сессии в этом месяце</small><strong>${monthSessions}</strong><span>сохранённых протоколов</span></article>
   <article class="metric-card"><small>Открытые шаги</small><strong>${openTasks}</strong><span>договорённостей в работе</span></article>
   <article class="metric-card"><small>Фокус внимания</small><strong>${attention}</strong><span>клиентов с пометкой</span></article>
  </div>
  <div class="dashboard-lower">
   <section class="panel clients-panel"><div class="panel-head"><div><span class="section-label">Последние записи</span><h2>Сессии</h2></div><button class="quiet-button" data-action="add-session">＋ Новая сессия</button></div>${recent.length?`<table class="client-table"><thead><tr><th>Клиент</th><th>Дата</th><th>Тема</th><th>Динамика</th></tr></thead><tbody>${recent.map(s=>{const c=clientById(s.clientId);return `<tr data-action="open-client" data-id="${s.clientId}"><td><div class="client-cell"><span class="avatar">${initials(c?.name)}</span><div><strong>${esc(c?.name||'Удалённый клиент')}</strong><small>${esc(s.format)}</small></div></div></td><td>${shortDate(s.date)}</td><td>${esc(truncate(s.theme,55))}</td><td>${s.stateBefore} → <strong>${s.stateAfter}</strong></td></tr>`}).join('')}</tbody></table>`:'<div class="empty-state"><strong>Протоколов пока нет</strong></div>'}</section>
   <section class="panel tasks-panel"><div class="panel-head"><div><span class="section-label">Договорённости</span><h2>Ближайшие шаги</h2></div><button class="text-button" data-action="view-plan">Весь план</button></div><div class="task-list">${renderTaskItems(6)}</div></section>
  </div>`;
}

function renderTaskItems(limit=99,clientId=null){
 const items=[];data.goals.filter(g=>!clientId||g.clientId===clientId).forEach(g=>(g.steps||[]).forEach(st=>items.push({goal:g,step:st})));
 const shown=items.filter(x=>!x.step.done).slice(0,limit);
 if(!shown.length)return '<div class="empty-state"><strong>Открытых шагов нет</strong><p>Добавьте договорённость в план работы.</p></div>';
 return shown.map(({goal,step})=>{const c=clientById(goal.clientId);return `<article class="task-item"><button class="check-button" data-action="toggle-step" data-goal="${goal.id}" data-step="${step.id}" aria-label="Отметить выполненным"></button><div><strong>${esc(step.text)}</strong><p>${esc(c?.name||'')} · ${esc(truncate(goal.title,55))}</p></div><small>${goal.deadline?shortDate(goal.deadline):'—'}</small></article>`}).join('');
}

function renderClients(root){
 setPage('Клиентская база','Клиенты');
 const q=ui.clientSearch.toLowerCase();const list=data.clients.filter(c=>(ui.clientStatus==='all'||c.status===ui.clientStatus)&&(!q||[c.name,c.request,c.contact].join(' ').toLowerCase().includes(q)));
 root.innerHTML=`<div class="page-heading"><div><span class="section-label">Карточки и история работы</span><h2>Клиенты</h2><p>Запрос, контекст, сессии, рабочие гипотезы, цели и динамика.</p></div><div class="toolbar"><input class="filter-input" id="clientSearch" value="${esc(ui.clientSearch)}" placeholder="Поиск по имени или запросу"><select class="filter-select" id="clientStatus"><option value="all">Все статусы</option><option value="active" ${ui.clientStatus==='active'?'selected':''}>В работе</option><option value="pause" ${ui.clientStatus==='pause'?'selected':''}>Пауза</option><option value="completed" ${ui.clientStatus==='completed'?'selected':''}>Завершено</option></select><button class="primary-button" data-action="add-client">＋ Новый клиент</button></div></div><div class="clients-grid">${list.length?list.map(renderClientCard).join(''):'<div class="empty-state"><strong>Ничего не найдено</strong><p>Измените фильтр или добавьте новую карточку.</p></div>'}</div>`;
 $('#clientSearch')?.addEventListener('input',e=>{ui.clientSearch=e.target.value;renderClients(root)});$('#clientStatus')?.addEventListener('change',e=>{ui.clientStatus=e.target.value;renderClients(root)});
}
function renderClientCard(c){const sessions=clientSessions(c.id);const goals=clientGoals(c.id).filter(g=>g.status!=='done').length;return `<article class="client-card" data-action="open-client" data-id="${c.id}"><div class="client-card-head"><div class="client-card-person"><span class="avatar">${initials(c.name)}</span><div><h3>${esc(c.name)}</h3><span class="status-chip ${statusClass(c.status)}">${statusLabels[c.status]}</span></div></div>${c.attention?'<span class="attention-chip">фокус</span>':''}</div><p>${esc(truncate(c.request||'Первичный запрос не заполнен',150))}</p><div class="client-card-meta"><span>${sessions.length} сессий</span><span>${goals} целей</span><span>${c.nextSession?shortDate(c.nextSession):'нет встречи'}</span></div></article>`}

function renderSessions(root){
 setPage('История работы','Сессии');const q=ui.sessionSearch.toLowerCase();const list=[...data.sessions].sort((a,b)=>b.date.localeCompare(a.date)).filter(s=>{const c=clientById(s.clientId);return !q||[s.theme,s.notes,c?.name].join(' ').toLowerCase().includes(q)});
 root.innerHTML=`<div class="page-heading"><div><span class="section-label">Структурированные протоколы</span><h2>Сессии</h2><p>Факты, гипотезы, интервенции и договорённости — без смешения уровней.</p></div><div class="toolbar"><input class="filter-input" id="sessionSearch" value="${esc(ui.sessionSearch)}" placeholder="Найти по клиенту или теме"><button class="primary-button" data-action="add-session">＋ Новая сессия</button></div></div><section class="panel sessions-panel"><div class="session-list">${list.length?list.map(renderSessionCard).join(''):'<div class="empty-state"><strong>Сессий пока нет</strong></div>'}</div></section>`;
 $('#sessionSearch')?.addEventListener('input',e=>{ui.sessionSearch=e.target.value;renderSessions(root)});
}
function renderSessionCard(s){const c=clientById(s.clientId);return `<article class="session-card"><div class="session-card-head"><div><h3>${esc(s.theme)}</h3><p>${esc(c?.name||'Удалённый клиент')} · ${fmtDate(s.date)} · ${esc(s.format)} · ${s.duration} мин</p></div><span class="meta-chip">состояние ${s.stateBefore} → ${s.stateAfter}</span></div><p>${esc(truncate(s.notes||s.hypothesis||'Протокол без заметок',220))}</p><div class="session-card-meta"><span class="meta-chip">гипотеза: ${esc(truncate(s.hypothesis||'не заполнена',65))}</span><span class="meta-chip">следующий фокус: ${esc(truncate(s.nextFocus||'не задан',55))}</span></div><div class="session-card-actions"><button data-action="edit-session" data-id="${s.id}">Редактировать</button><button data-action="session-report" data-id="${s.id}">Открыть протокол</button><button data-action="open-client" data-id="${s.clientId}">Карточка клиента</button></div></article>`}

function renderClient(root){
 const c=activeClient();if(!c){setView('clients');return}setPage('Карточка клиента',c.name);const sessions=clientSessions(c.id),goals=clientGoals(c.id),assess=clientAssessments(c.id);
 root.innerHTML=`<section class="panel dossier-header"><div class="dossier-top"><div class="dossier-person"><span class="avatar large">${initials(c.name)}</span><div><h2>${esc(c.name)}</h2><p>${c.age?`${c.age} лет · `:''}${esc(c.contact||'контакт не указан')} · <span class="status-chip ${statusClass(c.status)}">${statusLabels[c.status]}</span></p></div></div><div class="panel-actions"><button class="quiet-button" data-action="edit-client" data-id="${c.id}">Редактировать</button><button class="primary-button" data-action="add-session" data-client="${c.id}">Новая сессия</button></div></div><div class="dossier-summary"><div class="summary-box"><small>В работе с</small><strong>${fmtDate(c.createdAt)}</strong></div><div class="summary-box"><small>Сессий</small><strong>${sessions.length}</strong></div><div class="summary-box"><small>Следующая встреча</small><strong>${c.nextSession?`${fmtDate(c.nextSession,false)} ${c.nextSessionTime||''}`:'не назначена'}</strong></div><div class="summary-box"><small>Открытые шаги</small><strong>${goals.flatMap(g=>g.steps||[]).filter(x=>!x.done).length}</strong></div></div></section><nav class="tabs">${[['overview','Обзор'],['sessions','Сессии'],['assessment','Диагностика'],['plan','План'],['dynamics','Динамика']].map(([k,l])=>`<button class="${ui.clientTab===k?'active':''}" data-action="client-tab" data-tab="${k}">${l}</button>`).join('')}</nav><div id="clientTabRoot"></div>`;
 renderClientTab(c,sessions,goals,assess);
}
function renderClientTab(c,sessions,goals,assess){const root=$('#clientTabRoot');if(ui.clientTab==='overview')root.innerHTML=renderClientOverview(c,sessions,goals);else if(ui.clientTab==='sessions')root.innerHTML=`<section class="panel sessions-panel"><div class="panel-head"><div><span class="section-label">История встреч</span><h2>Сессии клиента</h2></div><button class="primary-button" data-action="add-session" data-client="${c.id}">＋ Добавить</button></div><div class="session-list">${sessions.length?sessions.map(renderSessionCard).join(''):'<div class="empty-state"><strong>Сессий пока нет</strong></div>'}</div></section>`;else if(ui.clientTab==='assessment')root.innerHTML=renderClientAssessments(c,assess);else if(ui.clientTab==='plan')root.innerHTML=renderClientPlan(c,goals);else root.innerHTML=renderClientDynamics(c,sessions)}
function editableBlock(c,key,label){return `<div class="field-block editable-field" data-field-wrap="${key}"><small>${label}</small><button class="edit-field-button" data-action="edit-field" data-field="${key}">Изменить</button><p>${c[key]?nl(c[key]):'<span style="color:#637b98">Не заполнено</span>'}</p></div>`}
function renderClientOverview(c,sessions,goals){const latest=sessions[0];return `<div class="dossier-grid"><section class="panel formulation-panel"><div class="panel-head"><div><span class="section-label">Рабочая карта</span><h2>Концептуализация случая</h2><p>Формулировки являются рабочими гипотезами и должны проверяться в диалоге.</p></div></div>${editableBlock(c,'request','Первичный запрос')}${editableBlock(c,'context','Контекст и значимые обстоятельства')}${editableBlock(c,'formulation','Рабочая гипотеза')}${editableBlock(c,'resources','Ресурсы и опоры')}${editableBlock(c,'constraints','Ограничения и условия')}${editableBlock(c,'attention','Фокус внимания / что не пропустить')}</section><aside><section class="panel timeline-panel"><div class="panel-head"><div><span class="section-label">Последняя встреча</span><h2>${latest?shortDate(latest.date):'Нет записей'}</h2></div></div>${latest?`<div class="field-block"><small>Тема</small><p>${nl(latest.theme)}</p></div><div class="field-block"><small>Изменение состояния</small><p>${latest.stateBefore} → ${latest.stateAfter}</p></div><div class="field-block"><small>Договорённость</small><p>${nl(latest.homework||'Не зафиксирована')}</p></div><button class="quiet-button" data-action="session-report" data-id="${latest.id}">Открыть протокол</button>`:'<div class="empty-state"><p>Добавьте первую сессию.</p></div>'}</section><section class="panel timeline-panel" style="margin-top:14px"><div class="panel-head"><div><span class="section-label">Быстрые действия</span><h2>Продолжить работу</h2></div></div><div class="quick-stack"><button class="primary-button" data-action="start-assessment" data-client="${c.id}">Провести диагностику</button><button class="quiet-button" data-action="add-goal" data-client="${c.id}">Добавить цель</button><button class="quiet-button" data-action="client-report" data-id="${c.id}">Сформировать отчёт</button></div>${c.attention?`<div class="attention-panel" style="margin-top:13px"><strong>Фокус внимания</strong><p>${nl(c.attention)}</p></div>`:''}</section></aside></div>`}
function renderClientAssessments(c,items){return `<section class="panel assessment-panel"><div class="panel-head"><div><span class="section-label">Карьерные маршруты</span><h2>Диагностика</h2><p>Психолог проводит вопросы вместе с клиентом и сохраняет вывод как материал для обсуждения.</p></div><button class="primary-button" data-action="start-assessment" data-client="${c.id}">Начать диагностику</button></div><div class="scenario-picker">${Object.entries(scenarios).map(([k,s])=>`<button class="scenario-tile" data-action="start-assessment" data-client="${c.id}" data-scenario="${k}"><span class="scenario-icon">${s.icon}</span><strong>${esc(s.short)}</strong><p>${esc(s.text)}</p></button>`).join('')}</div><div class="assessment-history"><span class="section-label">Сохранённые результаты</span>${items.length?items.map(a=>`<article class="assessment-card"><h3>${esc(scenarios[a.scenario]?.title||a.scenario)} · ${fmtDate(a.date)}</h3><p>${esc(truncate(a.result.headline,180))}</p><footer><button data-action="assessment-report" data-id="${a.id}">Открыть результат</button><button data-action="repeat-assessment" data-client="${c.id}" data-scenario="${a.scenario}">Повторить</button></footer></article>`).join(''):'<div class="empty-state" style="margin-top:10px"><p>Сохранённых результатов пока нет.</p></div>'}</div></section>`}
function renderClientPlan(c,goals){return `<section class="panel sessions-panel"><div class="panel-head"><div><span class="section-label">Рабочие цели</span><h2>План изменений</h2><p>Цель должна быть наблюдаемой, ограниченной по времени и связанной с реальным контекстом.</p></div><button class="primary-button" data-action="add-goal" data-client="${c.id}">＋ Новая цель</button></div>${goals.length?goals.map(renderGoalCard).join(''):'<div class="empty-state"><strong>Целей пока нет</strong></div>'}</section>`}
function renderGoalCard(g){const done=(g.steps||[]).filter(x=>x.done).length,total=(g.steps||[]).length,pct=total?Math.round(done/total*100):(g.status==='done'?100:0);return `<article class="goal-card ${g.status==='done'?'done':''}"><div class="goal-card-head"><div><h3>${esc(g.title)}</h3><p>${esc(g.metric||'Критерий продвижения не указан')}</p></div><span class="meta-chip">${g.deadline?fmtDate(g.deadline,false):'без срока'}</span></div><div class="goal-progress"><span style="width:${pct}%"></span></div><div class="goal-steps">${(g.steps||[]).map(st=>`<div class="goal-step ${st.done?'done':''}"><button class="check-button ${st.done?'done':''}" data-action="toggle-step" data-goal="${g.id}" data-step="${st.id}">${st.done?'✓':''}</button>${esc(st.text)}</div>`).join('')}</div><div class="goal-actions"><button data-action="add-goal-step" data-id="${g.id}">＋ шаг</button><button data-action="toggle-goal" data-id="${g.id}">${g.status==='done'?'Вернуть в работу':'Завершить цель'}</button><button data-action="delete-goal" data-id="${g.id}">Удалить</button></div></article>`}
function renderClientDynamics(c,sessions){return `<section class="panel chart-panel"><div class="panel-head"><div><span class="section-label">Самооценка состояния</span><h2>Динамика по сессиям</h2><p>График не измеряет терапевтический эффект. Он показывает только значения, зафиксированные в протоколах.</p></div></div>${renderChart(sessions)}<div class="legend"><span><i></i>до сессии</span><span><i class="after"></i>после сессии</span></div></section>`}

function renderAssessmentHub(root){const c=activeClient();setPage('Инструменты психолога','Диагностика');root.innerHTML=`<div class="page-heading"><div><span class="section-label">Пять карьерных маршрутов</span><h2>Совместная диагностика</h2><p>Сначала выберите клиента, затем маршрут. Результат прикрепится к его карточке.</p></div>${c?`<button class="primary-button" data-action="start-assessment" data-client="${c.id}">Начать для ${esc(c.name)}</button>`:''}</div><section class="panel assessment-panel"><div class="panel-head"><div><span class="section-label">Выбранный клиент</span><h2>${c?esc(c.name):'Клиент не выбран'}</h2></div><button class="quiet-button" data-action="view-clients">Сменить клиента</button></div><div class="scenario-picker">${Object.entries(scenarios).map(([k,s])=>`<button class="scenario-tile" data-action="start-assessment" data-client="${c?.id||''}" data-scenario="${k}" ${c?'':'disabled'}><span class="scenario-icon">${s.icon}</span><strong>${esc(s.title)}</strong><p>${esc(s.text)}</p></button>`).join('')}</div><div class="warning-box" style="margin-top:15px">Автоматический вывод не является заключением психолога. В рабочем процессе он используется как прозрачная гипотеза: ответы → логика → безопасный эксперимент → обсуждение с клиентом.</div></section>`}

function renderPlan(root){setPage('Цели и договорённости','План работы');const c=activeClient();root.innerHTML=`<div class="page-heading"><div><span class="section-label">Изменения, которые можно проверить</span><h2>План работы</h2><p>${c?`Сейчас показан план клиента ${esc(c.name)}.`:'Выберите клиента.'}</p></div><div class="toolbar"><button class="quiet-button" data-action="view-clients">Выбрать клиента</button>${c?`<button class="primary-button" data-action="add-goal" data-client="${c.id}">＋ Новая цель</button>`:''}</div></div>${c?renderClientPlan(c,clientGoals(c.id)):'<div class="empty-state"><strong>Нет выбранного клиента</strong></div>'}`}
function renderDynamics(root){setPage('Наблюдаемая динамика','Динамика');const c=activeClient();const sessions=c?clientSessions(c.id):[];root.innerHTML=`<div class="page-heading"><div><span class="section-label">Не оценка человека, а история наблюдений</span><h2>Динамика</h2><p>${c?`Клиент: ${esc(c.name)}.`:'Выберите клиента.'}</p></div><button class="quiet-button" data-action="view-clients">Сменить клиента</button></div>${c?renderClientDynamics(c,sessions):'<div class="empty-state"><strong>Нет выбранного клиента</strong></div>'}`}
function renderChart(sessions){const list=[...sessions].sort((a,b)=>a.date.localeCompare(b.date));if(!list.length)return '<div class="empty-state"><strong>Недостаточно данных</strong><p>Сохраните хотя бы одну сессию со шкалами состояния.</p></div>';const w=760,h=230,p=30;const x=i=>list.length===1?w/2:p+i*(w-2*p)/(list.length-1);const y=v=>h-p-(Number(v)||0)*(h-2*p)/10;const before=list.map((s,i)=>`${x(i)},${y(s.stateBefore)}`).join(' '),after=list.map((s,i)=>`${x(i)},${y(s.stateAfter)}`).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Динамика состояния по сессиям">${[0,2,4,6,8,10].map(v=>`<line x1="${p}" x2="${w-p}" y1="${y(v)}" y2="${y(v)}" stroke="#17324f"/><text class="chart-label" x="5" y="${y(v)+3}">${v}</text>`).join('')}<polyline class="chart-line-before" points="${before}"/><polyline class="chart-line-after" points="${after}"/>${list.map((s,i)=>`<circle class="chart-dot-before" cx="${x(i)}" cy="${y(s.stateBefore)}" r="4"/><circle class="chart-dot-after" cx="${x(i)}" cy="${y(s.stateAfter)}" r="4"/><text class="chart-label" text-anchor="middle" x="${x(i)}" y="${h-5}">${shortDate(s.date)}</text>`).join('')}</svg></div>`}

const templates=[
 {type:'Первая встреча',title:'Структура первичной сессии',text:'Запрос своими словами; желаемое изменение; контекст; что уже пробовали; ограничения; ресурсы; критерий полезности встречи; безопасный следующий шаг.'},
 {type:'Концептуализация',title:'Факт — интерпретация — гипотеза',text:'1. Что наблюдалось или было сказано. 2. Какой смысл этому придаёт клиент. 3. Какая рабочая гипотеза возникает. 4. Как её можно проверить без навязывания.'},
 {type:'Эксперимент',title:'Шаг на 72 часа',text:'Действие должно быть маленьким, обратимым и давать новую информацию. До начала фиксируются критерий результата, допустимые затраты и способ обсуждения.'},
 {type:'Завершение сессии',title:'Пять вопросов на выходе',text:'Что стало яснее? Что осталось неясным? Какой вывод клиент считает своим? Что он проверит? Что важно продолжить на следующей встрече?'},
 {type:'Супервизионная заметка',title:'Что я мог не заметить',text:'Где я ускорял клиента? Какое объяснение принял слишком рано? Какие альтернативы не проверил? Что вызвало сильную реакцию у меня? Какие границы компетенции актуальны?'},
 {type:'Этика данных',title:'Минимизация записей',text:'Фиксировать только то, что необходимо для профессиональной работы. Отделять факты от гипотез. Не хранить лишние идентифицирующие сведения. Регулярно удалять неактуальные копии.'}
];
function renderTemplates(root){setPage('Рабочие заготовки','Шаблоны');root.innerHTML=`<div class="page-heading"><div><span class="section-label">Не готовые ответы, а опоры мышления</span><h2>Шаблоны</h2><p>Короткие структуры для сессии, концептуализации, эксперимента и профессиональной рефлексии.</p></div></div><section class="panel templates-panel"><div class="templates-grid">${templates.map((t,i)=>`<article class="template-card"><span>${esc(t.type)}</span><h3>${esc(t.title)}</h3><p>${esc(t.text)}</p><button class="quiet-button" data-action="copy-template" data-index="${i}">Скопировать</button></article>`).join('')}</div></section>`}
function renderSettings(root){setPage('Данные и режим работы','Настройки');root.innerHTML=`<div class="page-heading"><div><span class="section-label">Локальная пилотная версия</span><h2>Настройки и резервная копия</h2><p>Приложение не использует сервер и не синхронизирует данные между устройствами.</p></div></div><div class="settings-grid"><section class="settings-card"><h3>Резервная копия</h3><p>Скачайте все карточки, сессии, цели и результаты диагностики одним JSON-файлом.</p><div class="panel-actions"><button class="primary-button" data-action="export-data">Скачать копию</button><button class="quiet-button" data-action="import-data">Восстановить</button></div></section><section class="settings-card"><h3>Отчёт по выбранному клиенту</h3><p>Создаёт печатную сводку без внутренних технических элементов интерфейса.</p><div class="panel-actions"><button class="quiet-button" data-action="client-report" data-id="${activeClient()?.id||''}" ${activeClient()?'':'disabled'}>Открыть отчёт</button></div></section><section class="settings-card"><h3>Демонстрационные данные</h3><p>Можно вернуть исходные примеры, чтобы безопасно показывать логику сервиса в портфолио.</p><div class="panel-actions"><button class="quiet-button" data-action="reset-demo">Восстановить демо</button></div></section><section class="settings-card"><h3>Удаление данных</h3><p>Удаляет всю локальную базу из этого браузера. Отменить действие после подтверждения нельзя.</p><div class="panel-actions"><button class="danger-button" data-action="delete-all">Удалить всё</button></div></section></div><div class="warning-box" style="margin-top:14px"><strong>Важно:</strong> локальное хранение в браузере не является системой защищённого медицинского документооборота. Для работы с реальными персональными данными необходимы авторизация, шифрование, резервное копирование, разграничение доступа, журнал действий и проверка соответствия применимому законодательству.</div>`}

function openClientForm(id=null){const f=$('#clientForm');f.reset();f.elements.id.value='';$('#clientModalTitle').textContent=id?'Редактирование клиента':'Новый клиент';if(id){const c=clientById(id);if(!c)return;Object.entries(c).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''})}openModal('#clientModal')}
function openSessionForm(id=null,clientId=null){const f=$('#sessionForm');f.reset();populateClientSelects();f.elements.id.value='';f.elements.date.value=todayISO();f.elements.duration.value=60;f.elements.stateBefore.value=5;f.elements.stateAfter.value=6;f.elements.stateBefore.nextElementSibling.textContent='5';f.elements.stateAfter.nextElementSibling.textContent='6';if(id){const s=data.sessions.find(x=>x.id===id);if(!s)return;Object.entries(s).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''});f.elements.stateBefore.nextElementSibling.textContent=s.stateBefore;f.elements.stateAfter.nextElementSibling.textContent=s.stateAfter;$('#sessionModalTitle').textContent='Редактирование сессии'}else{$('#sessionModalTitle').textContent='Новая сессия';f.elements.clientId.value=clientId||activeClient()?.id||''}openModal('#sessionModal')}
function openGoalForm(clientId=null){const f=$('#goalForm');f.reset();populateClientSelects();f.elements.id.value='';f.elements.clientId.value=clientId||activeClient()?.id||'';f.elements.deadline.value=isoOffset(14);openModal('#goalModal')}

function buildClientReport(c){const sessions=clientSessions(c.id),goals=clientGoals(c.id),assess=clientAssessments(c.id);return `<div class="report-header"><h1>Рабочая карта: ${esc(c.name)}</h1><p>Сформировано ${fmtDate(todayISO())}. Документ предназначен для профессиональной работы и требует проверки психологом.</p></div><div class="report-meta"><div><small>Статус</small><strong>${statusLabels[c.status]}</strong></div><div><small>Сессий</small><strong>${sessions.length}</strong></div><div><small>Следующая встреча</small><strong>${c.nextSession?`${fmtDate(c.nextSession,false)} ${c.nextSessionTime||''}`:'не назначена'}</strong></div></div>${[['Запрос',c.request],['Контекст',c.context],['Рабочая гипотеза',c.formulation],['Ресурсы',c.resources],['Ограничения',c.constraints],['Фокус внимания',c.attention]].map(([h,v])=>`<section class="report-section"><h2>${h}</h2><p>${nl(v||'Не заполнено')}</p></section>`).join('')}<section class="report-section"><h2>Цели и договорённости</h2>${goals.length?goals.map(g=>`<h3>${esc(g.title)}</h3><p>${esc(g.metric||'')}</p><ul>${(g.steps||[]).map(st=>`<li>${st.done?'✓':'○'} ${esc(st.text)}</li>`).join('')}</ul>`).join(''):'<p>Не заполнено.</p>'}</section><section class="report-section"><h2>Последние сессии</h2>${sessions.slice(0,8).map(s=>`<h3>${fmtDate(s.date)} — ${esc(s.theme)}</h3><p><strong>Наблюдения:</strong> ${nl(s.notes||'—')}<br><strong>Гипотеза:</strong> ${nl(s.hypothesis||'—')}<br><strong>Договорённость:</strong> ${nl(s.homework||'—')}</p>`).join('')||'<p>Нет сессий.</p>'}</section><section class="report-section"><h2>Рабочие сценарные карты</h2>${assess.map(a=>`<h3>${fmtDate(a.date)} — ${esc(scenarios[a.scenario]?.title||'Маршрут')}</h3><p>${nl(a.result.headline)}<br><strong>Проверяемый шаг:</strong> ${nl(a.result.step)}<br><strong>Комментарий психолога:</strong> ${nl(a.comment||'—')}</p>`).join('')||'<p>Нет результатов.</p>'}</section>`}
function openClientReport(id){const c=clientById(id);if(!c)return;$('#reportContent').innerHTML=buildClientReport(c);openModal('#reportModal')}
function openSessionReport(id){const s=data.sessions.find(x=>x.id===id);if(!s)return;const c=clientById(s.clientId);$('#reportContent').innerHTML=`<div class="report-header"><h1>Протокол сессии</h1><p>${esc(c?.name||'')} · ${fmtDate(s.date)} · ${esc(s.format)} · ${s.duration} минут</p></div><div class="report-meta"><div><small>Состояние до</small><strong>${s.stateBefore}/10</strong></div><div><small>Состояние после</small><strong>${s.stateAfter}/10</strong></div><div><small>Тема</small><strong>${esc(s.theme)}</strong></div></div>${[['Наблюдения и высказывания',s.notes],['Рабочая гипотеза',s.hypothesis],['Интервенции и вопросы',s.interventions],['Договорённость',s.homework],['Следующий фокус',s.nextFocus]].map(([h,v])=>`<section class="report-section"><h2>${h}</h2><p>${nl(v||'Не заполнено')}</p></section>`).join('')}`;openModal('#reportModal')}
function openAssessmentReport(id){const a=data.assessments.find(x=>x.id===id);if(!a)return;const c=clientById(a.clientId),r=a.result;$('#reportContent').innerHTML=`<div class="report-header"><h1>Рабочая сценарная карта</h1><p>${esc(c?.name||'')} · ${fmtDate(a.date)} · ${esc(scenarios[a.scenario]?.title||'')}</p></div><section class="report-section"><h2>Рабочая гипотеза</h2><p>${nl(r.headline)}</p></section><section class="report-section"><h2>Смысловой фокус</h2><p>${nl(r.route)}</p></section><section class="report-section"><h2>Шаг на 72 часа</h2><p>${nl(r.step)}</p></section><section class="report-section"><h2>Опора</h2><p>${nl(r.resource)}</p></section><section class="report-section"><h2>Логика результата</h2><p>${nl(r.why)}</p></section><section class="report-section"><h2>Комментарий психолога</h2><p>${nl(a.comment||'Не заполнено')}</p></section><section class="report-section"><p><strong>Ограничение:</strong> автоматический результат является материалом для обсуждения и не заменяет профессиональное заключение.</p></section>`;openModal('#reportModal')}

function label(scenario,key,value){const q=questionSets[scenario]?.find(x=>x.key===key);return q?.options.find(x=>x[0]===value)?.[1]||'трудно выбрать'}
function minutesFrom(value,def=30){return ({'10':10,'30':30,'60':60,talk:20,message:5,vacancies:10,resume:15,trial:30,'2h':30,day:30,days:45,unknown:15}[value]||def)}
function buildAssessmentResult(scenario,a){
 if(scenario==='hire'){
  let headline,route,step;const p=a.problem;
  if(p==='money'){headline='Менять профессию пока не обязательно: сначала стоит проверить рыночную цену работы.';route='сравнение рынка и условий';step='Сравнить оплату в трёх аналогичных вакансиях и подготовить один аргумент для разговора об условиях.'}
  else if(p==='growth'){headline='Тупик может быть связан не со всей профессией, а с отсутствием следующего уровня.';route='внутренний или внешний переход на следующий уровень';step=a.tried==='talk'||a.tried==='internal'?'Сравнить три вакансии следующего уровня у других работодателей.':'Запросить критерии перехода у руководителя и сохранить три внешние вакансии.'}
  else if(p==='manager'){headline='Проблема, вероятно, находится скорее в среде, чем в самой профессии.';route='та же роль в другой компании';step='Найти три вакансии с той же ролью и выписать признаки другой рабочей культуры.'}
  else if(p==='overload'){headline='Сейчас нужен не карьерный рывок, а проверка условий, которые истощают.';route='изменение нагрузки и границ';step='Зафиксировать три источника перегрузки и сформулировать один конкретный запрос об изменении приоритетов.'}
  else{headline='Вопрос касается содержания работы, а не только условий.';route='проверка смежного направления';step='Выбрать одну смежную роль и сравнить три реальные задачи с тем, что клиенту ещё интересно делать.'}
  return{headline,route,minutes:minutesFrom(a.time),step,resource:`Сохранить в переходе: ${label(scenario,'preserve',a.preserve).toLowerCase()}.`,why:`Главная проблема — «${label(scenario,'problem',p).toLowerCase()}», а потерять нельзя «${label(scenario,'protect',a.protect).toLowerCase()}». Поэтому первым шагом становится ${route}, а не резкое увольнение.`}
 }
 if(scenario==='return'){
  const steps={message:'Написать одному бывшему коллеге и узнать, что изменилось в сфере.',vacancies:'Сохранить три вакансии с гибким графиком и отметить уже имеющиеся требования.',resume:'Обновить один блок резюме: роль, три задачи и один результат.',trial:'Выполнить маленькую реальную задачу как пробу — не более 30 минут.'};
  return{headline:'Не нужно сразу возвращаться на полный день. Важнее выбрать темп, который выдержит реальная жизнь.',route:'мягкое возвращение без обнуления опыта',minutes:minutesFrom(a.step,10),step:steps[a.step]||steps.vacancies,resource:`Опора: ${label(scenario,'resource',a.resource).toLowerCase()}.`,why:`Сейчас важно «${label(scenario,'priority',a.priority).toLowerCase()}», при этом нельзя нарушить «${label(scenario,'protect',a.protect).toLowerCase()}». Поэтому первый шаг остаётся небольшим и обратимым.`}
 }
 if(scenario==='freelance'){
  let headline,route,step,mins=30;
  if(a.stage==='none'){headline='Сначала нужно проверить, существует ли спрос на конкретную задачу.';route='проверка спроса';step='Сформулировать одну проблему клиента и провести три коротких интервью.'}
  else if(a.stage==='rare'){headline='Редкие заказы ещё не образуют устойчивую систему: нужно проверить одно узкое место.';route=a.bottleneck==='leads'?'адресный поиск спроса':'точечная проверка узкого места';step=a.bottleneck==='sales'?'Переписать предложение через конкретный результат и показать трём людям.':a.bottleneck==='price'?'Посчитать время последнего заказа и назвать новую минимальную цену одному клиенту.':'Разобрать завершённый заказ и найти одну точку потери времени, денег или границ.'}
  else if(a.stage==='overload'){headline='Поток уже есть. Следующий рост — цена, границы и повторяемый процесс.';route='снижение ручной перегрузки';step=a.bottleneck==='boundaries'?'Записать три правила правок и отправить их следующему клиенту до начала работы.':'Превратить один повторяющийся этап в шаблон или фиксированную часть пакета.'}
  else{headline='Модель работает, но одно узкое место ограничивает доход или устойчивость.';route='оптимизация работающей модели';step='Разобрать последний проект по времени, этапам и бесплатным правкам и найти одну точку потери.'}
  if(a.duration==='unknown')mins=15;else if(a.duration==='days')mins=45;
  return{headline,route,minutes:mins,step,resource:`Повторяемая опора: ${label(scenario,'repeat',a.repeat).toLowerCase()}.`,why:`Стадия — «${label(scenario,'stage',a.stage).toLowerCase()}», узкое место — «${label(scenario,'bottleneck',a.bottleneck).toLowerCase()}». Поэтому маршрут начинается с ${route}.`}
 }
 if(scenario==='experienced'){
  let headline,route,step;
  if(a.reason==='load'){headline='Не нужна новая профессия с нуля. Нужно снизить нагрузку, сохранив экспертный капитал.';route=a.format==='mentor'?'наставничество или экспертно-методическая роль':'более спокойный формат той же экспертизы';step='Найти пять вакансий или проектов с меньшей операционной нагрузкой и отметить совпадающие результаты.'}
  else if(a.reason==='cut'){headline='Важно быстро перевести накопленный опыт в понятный рыночный язык.';route='та же или смежная роль без обнуления';step='Сохранить пять вакансий и выписать десять требований, уже подтверждённых опытом.'}
  else if(a.reason==='ceiling'){headline='Накопленный опыт, вероятно, перерос текущую роль.';route=a.format==='mentor'?'экспертная или наставническая роль':'следующий уровень в другой среде';step='Сравнить пять ролей следующего уровня и найти три доказательства готовности.'}
  else{headline='Менять нужно не весь профессиональный капитал, а способ его применения.';route=a.format==='project'?'проектная занятость':'смежная экспертная роль';step='Найти пять примеров выбранного формата и сравнить их задачи с актуальными интересами клиента.'}
  return{headline,route,minutes:a.horizon==='now'?30:45,step,resource:`Нельзя обнулить: ${label(scenario,'protect',a.protect).toLowerCase()}.`,why:`Причина перехода — «${label(scenario,'reason',a.reason).toLowerCase()}», доход нужен «${label(scenario,'horizon',a.horizon).toLowerCase()}», подходящий формат — «${label(scenario,'format',a.format).toLowerCase()}».`}
 }
 let headline,route,step;const weak=a.paid==='none'||a.evidence==='none';
 if(weak){headline='Опыт есть, но основание для отдельного продукта пока нужно подтвердить.';route='проверка проблемы и результата';step='Провести пять интервью и собрать два описания прошлых случаев, где помощь дала результат.'}
 else if(a.audience==='none'){headline='Метод имеет основания, но пилот пока некому предложить.';route='доступ к аудитории';step='Составить список пяти партнёров или сообществ и предложить короткий диагностический формат.'}
 else if(a.stage==='overload'){headline='Точка роста — вынести из индивидуальной работы один повторяемый и безопасный элемент.';route='продуктизация части метода';step='Собрать один повторяющийся этап в карточку, чек-лист или мини-диагностику.'}
 else{headline='Услуга имеет основание. Следующий шаг — проверить повторяемость и понятность предложения.';route='малый пилот с контролируемыми границами';step='Сформулировать один результат, аудиторию и границы и предложить двум людям платный разбор.'}
 return{headline,route,minutes:30,step,resource:`Опора: ${label(scenario,'evidence',a.evidence).toLowerCase()}.`,why:`Стадия — «${label(scenario,'stage',a.stage).toLowerCase()}», подтверждение — «${label(scenario,'evidence',a.evidence).toLowerCase()}», доступ к аудитории — «${label(scenario,'audience',a.audience).toLowerCase()}».`}
}

function startAssessment(clientId,scenario=null){if(!clientId||!clientById(clientId)){toast('Сначала выберите клиента');return}ui.assessmentDraft={clientId,scenario,step:scenario?0:-1,answers:{},result:null};const o=$('#assessmentOverlay');o.classList.add('open');o.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderAssessmentOverlay()}
function renderAssessmentOverlay(){const d=ui.assessmentDraft;if(!d)return;const c=clientById(d.clientId);$('#assessmentClientName').textContent=c?.name||'Клиент';const steps=$('#assessmentSteps');steps.innerHTML=(d.scenario?questionSets[d.scenario]:[]).map((q,i)=>`<span class="${d.step===i?'active':d.step>i?'done':''}"><i>${d.step>i?'✓':i+1}</i>${esc(q.kicker)}</span>`).join('')||Object.entries(scenarios).map(([k,s])=>`<span><i>${s.icon}</i>${esc(s.short)}</span>`).join('');
 if(d.step===-1){$('#assessmentScenarioLabel').textContent='Маршрут не выбран';$('#assessmentStepLabel').textContent='Выберите сценарий';$('#assessmentProgressFill').style.width='0%';$('#assessmentControls').style.display='none';$('#assessmentBody').innerHTML=`<section class="assessment-content"><span class="section-label">Совместная диагностика</span><h2>Какую карьерную ситуацию вы разбираете?</h2><p>Выберите маршрут. Вопросы и логика результата будут отличаться.</p><div class="scenario-choice-grid">${Object.entries(scenarios).map(([k,s])=>`<button class="scenario-tile" data-assessment-scenario="${k}"><span class="scenario-icon">${s.icon}</span><strong>${esc(s.title)}</strong><p>${esc(s.text)}</p></button>`).join('')}</div></section>`;$$('[data-assessment-scenario]').forEach(b=>b.onclick=()=>{d.scenario=b.dataset.assessmentScenario;d.step=0;renderAssessmentOverlay()});return}
 if(d.result){renderAssessmentResult();return}
 const q=questionSets[d.scenario][d.step],current=d.answers[q.key];$('#assessmentScenarioLabel').textContent=scenarios[d.scenario].title;$('#assessmentStepLabel').textContent=`Шаг ${d.step+1} из 5`;$('#assessmentProgressFill').style.width=`${(d.step+1)*20}%`;$('#assessmentControls').style.display='flex';$('#assessmentBack').style.visibility=d.step===0?'hidden':'visible';$('#assessmentNext').disabled=!current;$('#assessmentNext').textContent=d.step===4?'Показать результат →':'Продолжить →';$('#assessmentBody').innerHTML=`<section class="assessment-content"><span class="section-label">${esc(q.kicker)}</span><h2>${esc(q.title)}</h2><p>${esc(q.help)}</p><div class="answers-grid">${q.options.map(([v,l])=>`<button class="answer-button ${current===v?'selected':''}" data-answer="${v}">${esc(l)}</button>`).join('')}</div></section>`;$$('[data-answer]').forEach(b=>b.onclick=()=>{d.answers[q.key]=b.dataset.answer;renderAssessmentOverlay()})}
function renderAssessmentResult(){const d=ui.assessmentDraft,r=d.result;$('#assessmentScenarioLabel').textContent=scenarios[d.scenario].title;$('#assessmentStepLabel').textContent='Предварительная карта';$('#assessmentProgressFill').style.width='100%';$('#assessmentControls').style.display='none';$('#assessmentSteps').innerHTML=questionSets[d.scenario].map((q,i)=>`<span class="done"><i>✓</i>${esc(q.kicker)}</span>`).join('');$('#assessmentBody').innerHTML=`<section class="assessment-content assessment-result"><article class="assessment-result-hero"><span class="section-label">Предварительный вывод</span><h2>${esc(r.headline)}</h2><p>Автоматическая формулировка должна быть проверена в разговоре с клиентом.</p></article><article class="assessment-result-card"><span class="section-label">Предполагаемый маршрут</span><strong>${esc(r.route)}</strong><p>${esc(r.why)}</p></article><article class="assessment-result-card"><span class="section-label">Проверяемый шаг на 72 часа</span><strong>${esc(r.step)}</strong><p>${esc(r.resource)}</p></article><label class="assessment-comment"><span class="section-label">Комментарий психолога</span><textarea id="assessmentComment" placeholder="Что подтверждается в разговоре, с чем клиент не согласен, что важно проверить дальше"></textarea></label><div class="panel-actions"><button class="quiet-button" id="changeAssessmentAnswers">Изменить ответы</button><button class="primary-button" id="saveAssessment">Сохранить в карточку клиента</button></div><div class="warning-box">Результат не является диагнозом, психометрическим заключением или гарантией карьерного решения.</div></section>`;$('#changeAssessmentAnswers').onclick=()=>{d.result=null;d.step=4;renderAssessmentOverlay()};$('#saveAssessment').onclick=()=>{const item={id:uid('assessment'),clientId:d.clientId,date:todayISO(),scenario:d.scenario,answers:{...d.answers},result:{...d.result},comment:$('#assessmentComment').value.trim()};data.assessments.push(item);saveData();closeAssessment();data.activeClientId=d.clientId;ui.view='client';ui.clientTab='assessment';renderView();toast('Результат сохранён в карточке клиента')}}
function closeAssessment(){const o=$('#assessmentOverlay');o.classList.remove('open');o.setAttribute('aria-hidden','true');document.body.style.overflow='';ui.assessmentDraft=null}

function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tochka-opory-backup-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Резервная копия создана')}

$('#clientForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,fd=Object.fromEntries(new FormData(f));let c=clientById(fd.id);if(c){Object.assign(c,{name:fd.name.trim(),age:Number(fd.age)||'',contact:fd.contact.trim(),status:fd.status,request:fd.request.trim(),context:fd.context.trim(),nextSession:fd.nextSession,nextSessionTime:fd.nextSessionTime})}else{c={id:uid('client'),name:fd.name.trim(),age:Number(fd.age)||'',contact:fd.contact.trim(),status:fd.status,request:fd.request.trim(),context:fd.context.trim(),formulation:'',resources:'',constraints:'',attention:'',nextSession:fd.nextSession,nextSessionTime:fd.nextSessionTime,createdAt:todayISO()};data.clients.unshift(c);data.activeClientId=c.id}saveData();closeModal('#clientModal');ui.view='client';ui.clientTab='overview';renderView();toast('Карточка клиента сохранена')});
$('#sessionForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,fd=Object.fromEntries(new FormData(f));let s=data.sessions.find(x=>x.id===fd.id);const payload={clientId:fd.clientId,date:fd.date,format:fd.format,duration:Number(fd.duration)||60,stateBefore:Number(fd.stateBefore),stateAfter:Number(fd.stateAfter),theme:fd.theme.trim(),notes:fd.notes.trim(),hypothesis:fd.hypothesis.trim(),interventions:fd.interventions.trim(),homework:fd.homework.trim(),nextFocus:fd.nextFocus.trim()};if(s)Object.assign(s,payload);else data.sessions.push({id:uid('session'),...payload});data.activeClientId=fd.clientId;saveData();closeModal('#sessionModal');ui.view='client';ui.clientTab='sessions';renderView();toast('Протокол сессии сохранён')});
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,fd=Object.fromEntries(new FormData(f));data.goals.push({id:uid('goal'),clientId:fd.clientId,title:fd.title.trim(),metric:fd.metric.trim(),deadline:fd.deadline,status:'active',steps:fd.firstStep.trim()?[{id:uid('step'),text:fd.firstStep.trim(),done:false}]:[]});data.activeClientId=fd.clientId;saveData();closeModal('#goalModal');ui.view='client';ui.clientTab='plan';renderView();toast('Цель добавлена')});

$('#assessmentNext').addEventListener('click',()=>{const d=ui.assessmentDraft;if(!d||d.step<0)return;const q=questionSets[d.scenario][d.step];if(!d.answers[q.key])return;if(d.step<4){d.step++;renderAssessmentOverlay()}else{d.result=buildAssessmentResult(d.scenario,d.answers);renderAssessmentOverlay()}});
$('#assessmentBack').addEventListener('click',()=>{const d=ui.assessmentDraft;if(!d)return;if(d.step>0){d.step--;renderAssessmentOverlay()}});
$('#closeAssessment').addEventListener('click',()=>{if(confirm('Закрыть диагностику? Несохранённые ответы будут удалены.'))closeAssessment()});
$('#printReport').addEventListener('click',()=>window.print());

$('#viewRoot').addEventListener('click',async e=>{
 const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(a==='add-client')openClientForm();
 else if(a==='edit-client')openClientForm(b.dataset.id);
 else if(a==='add-session')openSessionForm(null,b.dataset.client||activeClient()?.id);
 else if(a==='edit-session')openSessionForm(b.dataset.id);
 else if(a==='add-goal')openGoalForm(b.dataset.client||activeClient()?.id);
 else if(a==='open-client'){if(clientById(b.dataset.id)){data.activeClientId=b.dataset.id;saveData();ui.view='client';ui.clientTab='overview';renderView()}}
 else if(a==='open-active-client'){ui.view='client';ui.clientTab='overview';renderView()}
 else if(a==='view-clients')setView('clients');else if(a==='view-sessions')setView('sessions');else if(a==='view-plan')setView('plan');
 else if(a==='client-tab'){ui.clientTab=b.dataset.tab;renderClient($('#viewRoot'))}
 else if(a==='edit-field'){const c=activeClient(),key=b.dataset.field,wrap=b.closest('[data-field-wrap]');wrap.innerHTML=`<small>${wrap.querySelector('small').textContent}</small><div class="inline-editor"><textarea>${esc(c[key]||'')}</textarea><div class="inline-editor-actions"><button class="quiet-button" data-action="cancel-field">Отмена</button><button class="primary-button" data-action="save-field" data-field="${key}">Сохранить</button></div></div>`}
 else if(a==='cancel-field')renderView();
 else if(a==='save-field'){const c=activeClient();c[b.dataset.field]=b.closest('[data-field-wrap]').querySelector('textarea').value.trim();saveData();renderView();toast('Поле обновлено')}
 else if(a==='start-assessment'||a==='repeat-assessment')startAssessment(b.dataset.client||activeClient()?.id,b.dataset.scenario||null);
 else if(a==='toggle-step'){const g=data.goals.find(x=>x.id===b.dataset.goal),st=g?.steps.find(x=>x.id===b.dataset.step);if(st){st.done=!st.done;saveData();renderView()}}
 else if(a==='toggle-goal'){const g=data.goals.find(x=>x.id===b.dataset.id);if(g){g.status=g.status==='done'?'active':'done';saveData();renderView()}}
 else if(a==='add-goal-step'){const g=data.goals.find(x=>x.id===b.dataset.id);if(g){const text=prompt('Новый шаг:');if(text?.trim()){g.steps.push({id:uid('step'),text:text.trim(),done:false});saveData();renderView()}}}
 else if(a==='delete-goal'){if(confirm('Удалить цель и её шаги?')){data.goals=data.goals.filter(x=>x.id!==b.dataset.id);saveData();renderView()}}
 else if(a==='session-report')openSessionReport(b.dataset.id);else if(a==='client-report')openClientReport(b.dataset.id||activeClient()?.id);else if(a==='assessment-report')openAssessmentReport(b.dataset.id);
 else if(a==='copy-template'){const t=templates[Number(b.dataset.index)];try{await navigator.clipboard.writeText(`${t.title}\n\n${t.text}`);toast('Шаблон скопирован')}catch{toast('Не удалось скопировать')}}
 else if(a==='export-data')exportData();else if(a==='import-data')$('#importFile').click();
 else if(a==='reset-demo'){if(confirm('Заменить текущие данные демонстрационными?')){data=seedData();saveData();setView('dashboard');toast('Демо-данные восстановлены')}}
 else if(a==='delete-all'){if(confirm('Удалить все локальные данные?')){data={version:1,activeClientId:null,clients:[],sessions:[],goals:[],assessments:[]};saveData();setView('dashboard');toast('Все данные удалены')}}
});

$('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.version!==1||!Array.isArray(parsed.clients))throw new Error();if(confirm('Заменить текущие данные содержимым резервной копии?')){data=parsed;saveData();setView('dashboard');toast('Резервная копия восстановлена')}}catch{alert('Файл не похож на резервную копию «Точки опоры».')}e.target.value=''});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
$('#quickAddClient').addEventListener('click',()=>openClientForm());$('#quickAddSession').addEventListener('click',()=>openSessionForm());
$('#activeClientMini').addEventListener('click',e=>{const b=e.target.closest('[data-mini-action]');if(!b)return;if(b.dataset.miniAction==='open'){ui.view='client';ui.clientTab='overview';renderView()}else openSessionForm(null,activeClient()?.id)});
$$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal'))));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal.open').forEach(closeModal);if($('#assessmentOverlay').classList.contains('open')&&confirm('Закрыть диагностику без сохранения?'))closeAssessment()}});
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim();if(!q)return;if(ui.view!=='clients'){ui.clientSearch=q;ui.view='clients';renderView()}else{ui.clientSearch=q;renderView()}});

refreshChrome();renderView();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
